### ISSUE TITLE
Feature: Strict Mode, or only with '@'

### ISSUE THREAD

**Issue by pmkroeker** [kamranahmedse/git-pending#1]
First off thanks! This is amazing and I look forward to using it more in the future.

I was wondering if there could be an added option for 'strict' mode or something of that nature, where the tags (todo, fixme etc) must start with an '@' sign, so it will only match locations like `@todo`.

I have found that some old libs that we have committed have 'TODO' scattered around and it would be nice to have a way for more strict checking.

Another possibility could be a list of ignored files/directories.

**Comment by kamranahmedse** [comment]
Thank you - this has been added in `1.1.0`

**Comment by pmkroeker** [comment]
Amazing thanks so much!
